### ISSUE TITLE
create action that generates release binary for all platforms

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/EdgeML-Arduino#5]
we need an action that builds the binary firmware file for Nicla, Nano and Seed so they can be pulled from edge-ml for OTA flashing, maybe directly from github so they are always up to date.

**Comment by tk-king** [comment]
Add functionality to flash over BLE with this firmware.

**Comment by tk-king** [comment]
- [ ] Compile the firmware using Github actions and store the binary files on Github.
- [ ] Implement dfu mode in the firmware to flash firmare updates over and over again.

**Comment by tk-king** [comment]
DFU implemented in the branch `feature/dfuFlash`
